# Faculty Advisor Agentic System Configuration

# System settings
environment: development
debug: true
log_level: INFO
secret_key: faculty-advisor-secret-key-change-in-production
session_timeout_minutes: 60
allowed_email_domains:
  - amrita.edu

# Database configuration
database:
  host: localhost
  port: 5432
  database: faculty_advisor
  username: postgres
  password: ""
  pool_size: 10
  max_overflow: 20

# Redis configuration (for session management and short-term memory)
redis:
  host: localhost
  port: 6379
  database: 0
  password: ""
  max_connections: 10

# LLM configuration (Ollama)
llm:
  provider: ollama
  model_name: llama3.1
  base_url: http://localhost:11434
  temperature: 0.7
  max_tokens: 1000
  timeout: 30

# Agent-specific configurations
agents:
  orchestrator:
    max_concurrent_requests: 100
    request_timeout: 30
    
  solution_advisory:
    rag_top_k: 5
    confidence_threshold: 0.7
    
  leave_management:
    max_leave_days: 30
    approval_timeout_hours: 48
    
  monitoring:
    check_interval_minutes: 5
    alert_threshold_cgpa: 6.0
    alert_threshold_attendance: 75
    
  communications:
    email_batch_size: 50
    retry_attempts: 3
    retry_delay_seconds: 60